name: encrypt
version: 5.0.5
description: A set of high-level APIs over PointyCastle for two-way cryptography.
repository: https://github.com/leocavalcante/encrypt

executables:
  secure-random:

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.7.0
  asn1lib: ^1.6.5
  clock: ^1.1.2
  collection: ^1.19.0
  crypto: ^3.0.7
  pointycastle: ^4.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0

false_secrets:
 - /test/*.pem
